// =====================================================
// CYCLES PAGE
// =====================================================
const cycleTable = document.getElementById("cycleTable"), cycleModal = document.getElementById("cycleModal"), cycleForm = document.getElementById("cycleForm");
function getRecipientForCycle(cycle) { return getMembers().find(m => m.id === cycle?.recipientId) || getNextRecipient(cycle); }
function renderCycles() {
  const active = getActiveCycle(), members = getMembers(), collected = active ? getCycleCollected(active.id) : 0, target = active?.target || 0, percent = target ? Math.min(100, Math.round(collected / target * 100)) : 0;
  const recipient = getRecipientForCycle(active);
  document.getElementById("activeCycleName").textContent = active ? `#${active.number}` : "None";
  document.getElementById("activeCycleDates").textContent = active ? `${formatDate(active.startDate)} - ${formatDate(active.endDate)}` : "-";
  document.getElementById("cyclePool").textContent = formatMoney(collected); document.getElementById("cycleTarget").textContent = `Target: ${formatMoney(target)}`;
  document.getElementById("recipientName").textContent = recipient?.name || "-"; document.getElementById("recipientPosition").textContent = `Rotation position: ${recipient?.rotationPosition || "-"}`;
  document.getElementById("cyclePercent").textContent = percent + "%"; document.getElementById("cycleProgress").textContent = percent + "%"; document.getElementById("activeTitle").textContent = active ? `Cycle #${active.number}` : "No active cycle";
  document.getElementById("progressBar").style.width = percent + "%"; document.getElementById("progressCollected").textContent = `${formatMoney(collected)} collected`; document.getElementById("progressPercent").textContent = percent + "%";
  document.getElementById("startDate").textContent = active ? formatDate(active.startDate) : "-"; document.getElementById("endDate").textContent = active ? formatDate(active.endDate) : "-";
  const paidIds = new Set(getCycleContributions(active?.id).map(p => p.memberId)); document.getElementById("paidMembers").textContent = `${paidIds.size} / ${members.filter(m => m.enrolled).length}`; document.getElementById("recipientDetail").textContent = recipient?.name || "-";
  document.getElementById("closeCycleButton").disabled = !active; document.getElementById("closeCycleButton").style.opacity = active ? "1" : ".5"; document.getElementById("sideCycle").textContent = active ? `Cycle #${active.number}` : "No active cycle";
  cycleTable.innerHTML = ""; getCycles().sort((a, b) => Number(b.number) - Number(a.number)).forEach(c => { const r = getRecipientForCycle(c); const row = document.createElement("tr"); row.innerHTML = `<td><strong>#${c.number}</strong></td><td>${formatDate(c.startDate)} - ${formatDate(c.endDate)}</td><td>${formatMoney(c.target)}</td><td>${formatMoney(getCycleCollected(c.id))}</td><td>${escapeHTML(r?.name || "-")}</td><td><span class="status ${c.status}">${c.status}</span></td>`; cycleTable.appendChild(row); });
}

function loadRecipients() { const select = document.getElementById("cycleRecipient"); select.innerHTML = ""; getMembers().filter(m => m.enrolled).sort((a, b) => a.rotationPosition - b.rotationPosition).forEach(m => { const o = document.createElement("option"); o.value = m.id; o.textContent = `#${m.rotationPosition} — ${m.name}`; select.appendChild(o); }); }
function openModal() { loadRecipients(); document.getElementById("cycleNumber").value = (Math.max(0, ...getCycles().map(c => Number(c.number))) + 1); cycleModal.classList.add("show"); cycleModal.setAttribute("aria-hidden", "false"); }
function closeModal() { cycleModal.classList.remove("show"); cycleModal.setAttribute("aria-hidden", "true"); cycleForm.reset(); }
document.getElementById("openCycle").addEventListener("click", openModal); document.getElementById("closeCycleModal").addEventListener("click", closeModal); document.getElementById("cancelCycle").addEventListener("click", closeModal); cycleModal.addEventListener("click", e => { if (e.target === cycleModal) closeModal(); });
cycleForm.addEventListener("submit", e => { e.preventDefault(); if (getActiveCycle()) { alert("Close the current cycle before creating a new one."); return; } const cycle = { id: Date.now().toString(), number: Number(document.getElementById("cycleNumber").value), target: Number(document.getElementById("cycleTargetInput").value), startDate: document.getElementById("cycleStart").value, endDate: document.getElementById("cycleEnd").value, recipientId: document.getElementById("cycleRecipient").value, status: "active" }; if (!cycle.number || cycle.target <= 0 || !cycle.startDate || !cycle.endDate || cycle.endDate < cycle.startDate) { alert("Please enter valid cycle details."); return; } saveCycles([...getCycles(), cycle]); closeModal(); renderCycles(); });

document.getElementById("closeCycleButton").addEventListener("click", () => { const active = getActiveCycle(); if (!active) return; const collected = getCycleCollected(active.id); const recipient = getRecipientForCycle(active); if (!confirm(`Close Cycle #${active.number}? The payout recipient is ${recipient?.name || "not selected"}. Pool: ${formatMoney(collected)}.`)) return; saveCycles(getCycles().map(c => c.id === active.id ? { ...c, status: "closed", closedAt: new Date().toISOString().slice(0, 10), payoutAmount: collected, recipientId: recipient?.id || c.recipientId } : c)); renderCycles(); alert("Cycle validated and closed. The record is now part of history."); });

document.getElementById("logoutButton").addEventListener("click", () => { localStorage.removeItem(DB_KEYS.loggedIn); location.href = "login.html"; }); const mobileMenu = document.getElementById("mobileMenu"), sidebar = document.getElementById("sidebar"), overlay = document.getElementById("sidebarOverlay"); mobileMenu.addEventListener("click", () => { sidebar.classList.toggle("open"); overlay.classList.toggle("show") }); overlay.addEventListener("click", () => { sidebar.classList.remove("open"); overlay.classList.remove("show") }); const savedUser = JSON.parse(localStorage.getItem("njangiDemoUser") || "null"); if (savedUser) { document.getElementById("userName").textContent = savedUser.name || "Njangi Admin"; document.getElementById("userAvatar").textContent = getInitials(savedUser.name); } renderCycles();
