// ============================================================
// ADMIN DASHBOARD - live data from the backend
// ============================================================
(async()=>{
 const admin=await requireAdmin();if(!admin)return;const $=id=>document.getElementById(id);$('userName').textContent=admin.name;$('welcomeName').textContent=admin.name.split(' ')[0];$('userAvatar').textContent=initials(admin.name);
 async function render(){const d=await api('/dashboard');const c=d.cycle;const progress=d.stats.progress;$('totalPool').textContent=money(d.stats.totalPool);$('totalMembers').textContent=d.stats.totalMembers;$('progressValue').textContent=progress+'%';$('collectedAmount').textContent=money(c?.collected||0);$('progressFill').style.width=progress+'%';$('remainingAmount').textContent=money(Math.max(Number(c?.target||0)-Number(c?.collected||0),0))+' remaining';$('progressText').textContent=progress+'%';document.querySelector('#cycles h2').textContent=c?`Cycle #${c.number}`:'No active cycle';document.querySelector('#cycles .cycle-amounts div:nth-child(2) strong').textContent=money(c?.target||0);document.querySelector('#cycles .cycle-details div:nth-child(1) strong').textContent=c?formatDate(c.startDate):'-';document.querySelector('#cycles .cycle-details div:nth-child(2) strong').textContent=c?`${c.paidMembers} / ${d.stats.totalMembers}`:'0 / 0';document.querySelector('#cycles .status').textContent=c?'Active':'None';document.querySelector('#cycles .status').className='status '+(c?'active':'');document.querySelector('.stat-box:nth-child(3) h2').textContent=c?`Cycle #${c.number}`:'None';document.querySelector('.stat-box:nth-child(3) p').textContent=c?'Target: '+money(c.target):'No active cycle';document.querySelector('.stat-box:nth-child(4) p').textContent=money(c?.collected||0)+' of '+money(c?.target||0);
 const list=$('memberList');list.innerHTML='';d.members.slice(0,8).forEach(m=>{const div=document.createElement('div');div.className='member-row';div.innerHTML=`<div class="member-main"><span class="mini-avatar">${initials(m.name)}</span><div><strong>${safe(m.name)}</strong><small>${m.reliability.score}% reliability</small></div></div><span class="payment-status ${statusClass(m.status)}">${safe(m.status)}</span>`;list.appendChild(div);});
 const table=$('contributionTable');table.innerHTML='';d.recentContributions.forEach(c=>{const tr=document.createElement('tr');const member=d.members.find(m=>m.id===c.memberId);tr.innerHTML=`<td><strong>${safe(c.memberName)}</strong></td><td>${money(c.amount)}</td><td>${formatDate(c.date)}</td><td><span class="payment-status paid">${c.date<=c.dueDate?'On time':'Late'}</span></td>`;table.appendChild(tr);});
 document.querySelector('.group-switcher span').textContent=c?`Cycle #${c.number}`:'No active cycle';
 }
 $('addContributionButton').onclick=()=>location.href='contributions.html';$('viewCycleButton').onclick=()=>location.href='cycles.html';document.querySelectorAll('.quick-card').forEach((b,i)=>b.onclick=()=>location.href=['members.html','contributions.html','cycles.html'][i]);$('memberSearch').oninput=async()=>{const q=$('memberSearch').value.toLowerCase();const d=await api('/dashboard');const matches=d.members.filter(m=>m.name.toLowerCase().includes(q));const list=$('memberList');list.innerHTML=matches.map(m=>`<div class="member-row"><div class="member-main"><span class="mini-avatar">${initials(m.name)}</span><div><strong>${safe(m.name)}</strong><small>${m.reliability.score}% reliability</small></div></div><span class="payment-status ${statusClass(m.status)}">${safe(m.status)}</span></div>`).join('');};$('mobileMenu').onclick=()=>{$('sidebar').classList.toggle('open');$('sidebarOverlay').classList.toggle('show');};$('sidebarOverlay').onclick=()=>{$('sidebar').classList.remove('open');$('sidebarOverlay').classList.remove('show');};$('logoutButton').onclick=async()=>{try{await post('/auth/logout',{},'admin');}catch{}clearToken('admin');location.href='login.html';};await render();
})();
