// ============================================================
// HISTORY PAGE
// ============================================================
(async()=>{
 const admin=await requireAdmin();if(!admin)return;const $=id=>document.getElementById(id);let data={contributions:[],cycles:[]};
 async function load(){data=await api('/history');const members=[...new Map(data.contributions.map(c=>[c.memberId,{id:c.memberId,name:c.memberName}])).values()];$('memberFilter').innerHTML='<option value="">All members</option>'+members.map(m=>`<option value="${m.id}">${safe(m.name)}</option>`).join('');render();}
 function render(){const q=$('historySearch').value.toLowerCase().trim(),member=$('memberFilter').value,date=$('dateFilter').value;let rows=data.contributions.filter(c=>(!q||c.memberName.toLowerCase().includes(q))&&(!member||c.memberId===member)&&(!date||c.date===date));$('historyTotal').textContent=money(data.contributions.reduce((s,c)=>s+Number(c.amount),0));$('historyCount').textContent=data.contributions.length;$('historyMembers').textContent=new Set(data.contributions.map(c=>c.memberId)).size;$('historyCycles').textContent=data.cycles.length;$('historyBody').innerHTML='';$('emptyHistory').style.display=rows.length?'none':'flex';rows.forEach(c=>{const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${safe(c.memberName)}</strong></td><td>${money(c.amount)}</td><td>${formatDate(c.date)}</td><td>Cycle #${c.cycleNumber}</td><td>Contribution</td>`;$('historyBody').appendChild(tr);});}
 $('historySearch').oninput=render;$('memberFilter').onchange=render;$('dateFilter').onchange=render;$('resetFilter').onclick=()=>{$('memberFilter').value='';$('dateFilter').value='';render();};$('clearHistory').onclick=()=>alert('For safety, individual contribution records are deleted from the Contributions page.');$('mobileMenu').onclick=()=>{$('sidebar').classList.toggle('open');$('sidebarOverlay').classList.toggle('show');};$('sidebarOverlay').onclick=()=>{$('sidebar').classList.remove('open');$('sidebarOverlay').classList.remove('show');};$('logoutButton').onclick=async()=>{try{await post('/auth/logout',{},'admin');}catch{}clearToken('admin');location.href='login.html';};await load();
})();
