// ============================================================
// EMERGENCY LOANS - admin page
// Approval is decided by the backend reliability rules.
// Reliability = on-time completed cycles / completed cycles.
// ============================================================
(async () => {
  const admin = await requireAdmin(); if (!admin) return; const $ = id => document.getElementById(id); $('userName').textContent = admin.name; $('userAvatar').textContent = initials(admin.name); let members = [];
  async function load() { const [m, r] = await Promise.all([api('/members'), api('/reliability')]); members = m.members; loadMembers(); renderReliability(r); await renderLoans(); }
  function loadMembers() { const s = $('loanMember'); s.innerHTML = ''; members.forEach(m => { const o = document.createElement('option'); o.value = m.id; o.textContent = m.name; s.appendChild(o); }); }
  async function renderLoans() { const filter = $('statusFilter').value; const d = await api('/loans' + (filter && filter !== 'all' ? `?status=${encodeURIComponent(filter)}` : '')); const loans = d.loans; $('loanTableBody').innerHTML = ''; $('emptyState').style.display = loans.length ? 'none' : 'block'; loans.forEach(l => { const tr = document.createElement('tr'); const rel = l.reliability; tr.innerHTML = `<td><strong>${safe(l.memberName)}</strong><small class="loan-score">Score: ${rel.score}%</small></td><td>${money(l.requestedAmount)}</td><td>${safe(l.reason)}</td><td>${formatDate(l.requestedAt)}</td><td>${money(l.balance)}</td><td><span class="status ${statusClass(l.status)}">${safe(cap(l.status))}</span></td><td>${actions(l)}</td>`; $('loanTableBody').appendChild(tr); }); updateSummary(d.loans); }
  function actions(l) { if (l.status === 'pending') return `<button class="action-btn approve-btn" onclick="approveLoan('${l.id}')">Approve</button><button class="action-btn reject-btn" onclick="rejectLoan('${l.id}')">Reject</button><button class="action-btn delete-btn" onclick="deleteLoan('${l.id}')">Delete</button>`; if (l.status === 'approved') return `<button class="action-btn payment-btn" onclick="openPayment('${l.id}')">Record Payment</button><button class="action-btn delete-btn" onclick="deleteLoan('${l.id}')">Delete</button>`; return `<button class="action-btn delete-btn" onclick="deleteLoan('${l.id}')">Delete</button>`; }
  function updateSummary(loans) { $('pendingCount').textContent = loans.filter(l => l.status === 'pending').length; $('activeBalance').textContent = money(loans.filter(l => l.status === 'approved').reduce((s, l) => s + l.balance, 0)); $('borrowerCount').textContent = new Set(loans.filter(l => l.status === 'approved').map(l => l.memberId)).size; $('averageReliability').textContent = members.length ? Math.round(members.reduce((s, m) => s + m.reliability.score, 0) / members.length) + '%' : '0%'; }
  function renderReliability(r) { $('reliabilityGrid').innerHTML = r.reliability.map(x => `<div class="reliability-card"><div class="reliability-top"><span class="reliability-name">${safe(x.member.name)}</span><span class="reliability-score">${x.score}%</span></div><div class="progress"><div class="progress-bar" style="width:${x.score}%"></div></div><div class="reliability-info"><span>On time: ${x.onTime}</span><span>Late: ${x.late}</span><span>Missed: ${x.missed}</span></div></div>`).join(''); }
  window.approveLoan = async id => { try { const r = await post(`/loans/${id}/approve`, {}); alert(`Approved. Reliability score: ${r.reliability.score}%.`); await load(); } catch (e) { if (e.data?.reliability) alert(`${e.message}\nScore: ${e.data.reliability.score}%\nOn time: ${e.data.reliability.onTime}\nLate: ${e.data.reliability.late}\nMissed: ${e.data.reliability.missed}`); else alert(e.message); } };
  window.rejectLoan = async id => { if (!confirm('Reject this loan request?')) return; try { await post(`/loans/${id}/reject`, {}); await load(); } catch (e) { alert(e.message); } };
  window.deleteLoan = async id => { if (!confirm('Delete this loan record?')) return; try { await del(`/loans/${id}`); await load(); } catch (e) { alert(e.message); } };
  window.openPayment = id => { const loanId = $('paymentLoanId'); loanId.value = id; const loanText = document.querySelector(`#loanTableBody button[onclick="openPayment('${id}')"]`); $('paymentDescription').textContent = 'Enter a repayment amount. The backend will update the balance.'; $('paymentModal').classList.add('show'); $('paymentAmount').value = ''; $('paymentAmount').focus(); };
  $('paymentForm').onsubmit = async e => { e.preventDefault(); try { await post(`/loans/${$('paymentLoanId').value}/payments`, { amount: Number($('paymentAmount').value) }); closePayment(); await load(); } catch (err) { alert(err.message); } }; function closePayment() { $('paymentModal').classList.remove('show'); } $('closePaymentModal').onclick = closePayment; $('cancelPayment').onclick = closePayment; $('paymentModal').onclick = e => { if (e.target.id === 'paymentModal') closePayment(); }; $('statusFilter').onchange = renderLoans;
  $('loanForm').onsubmit = async e => { e.preventDefault(); try { await post('/loans', { memberId: $('loanMember').value, amount: Number($('loanAmount').value), reason: $('loanReason').value.trim() }); e.target.reset(); await load(); } catch (err) { alert(err.message); } }; $('mobileMenu').onclick = () => { $('sidebar').classList.toggle('open'); $('overlay').classList.toggle('show'); }; $('overlay').onclick = () => { $('sidebar').classList.remove('open'); $('overlay').classList.remove('show'); }; $('logoutBtn').onclick = async () => { try { await post('/auth/logout', {}, 'admin'); } catch { } clearToken('admin'); location.href = 'login.html'; }; await load();
  function cap(s) { return s.charAt(0).toUpperCase() + s.slice(1); }
})();
